### ISSUE TITLE
Allow ConfZFileSource to be Optional

### ISSUE THREAD

**Issue by AndrewW85** [Zuehlke/ConfZ#39]
With the flexibility offered by ConfZ, there are cases where a file may be used in one context and not used or present in another.  Currently, if a file is not found at the specified path, then an exception is triggered.  It would be nice to have an added parameter in the signature like `optional=True` to allow for ignoring the exception and moving to the next source.

**Comment by silvanmelchior** [comment]
This would definitely be nice! I don't have the time to work on it right now, but if anyone wants to contribute, a PR would be very welcome! (We now also have mypy, black and pylint to support from the dev-side in this 😉)

**Comment by mglettig** [comment]
I like this idea. 👍 Because I think it would also allow the following use-case: Having multiple locations for the configuration with different priorities. Something like a local configuration and a default configuration (both file based) where the local configuration would have priority over the default configuration. If the local configuration would not be present the lib would silently parse the default configuration without an error.
