### ISSUE TITLE
Separator for env variables

### ISSUE THREAD

**Issue by kelvan** [Zuehlke/ConfZ#89]
first, thank you for your work, confz is very handy and makes my life much easier :)

When I tried to use nested env variables like GROUP.PARAM, I realized this could lead to problems, as (most?) shells won't allow using dots in var names with export (using direnv).

Using .env file (or docker env) works, maybe this is something worth to note in the docs.

**Comment by silvanmelchior** [comment]
Hey, thanks, good point, will do so with the next doc update 👍🏼

**Comment by rhorenov** [comment]
Hi guys,

I second this. I've just spent a far-too-much-time(TM) pondering why environment variables like `GROUP.PARAM` do not work in a Dockerized project when I define the environment in `docker-compose` instead of in a `.env` file.

Please consider updating the documentation to mention this ASAP.

Regards,
Roman
